ENV['PATH'] = "/usr/local/bin:/opt/homebrew/bin:#{ENV['PATH']}"
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

prepare_react_native_project!

# Manual Autolinking Bypass for hanging CLI
def manual_use_native_modules!
  package = JSON.parse(File.read('../package.json'))
  dependencies = (package['dependencies'] || {}).merge(package['devDependencies'] || {})
  
  dependencies.each do |name, version|
    next if name == 'react-native'
    # Find podspec in node_modules
    podspec_path = Dir.glob("../node_modules/#{name}/*.podspec").first
    if podspec_path
      pod_name = File.basename(podspec_path, ".podspec")
      Pod::UI.puts "[Manual Autolink] Found #{name} (as #{pod_name})".green
      pod pod_name, :path => "../node_modules/#{name}"
    end
  end
  return { :reactNativePath => '../node_modules/react-native' }
end

target 'multiuserauthapp' do
  config = manual_use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )
    # Disable Explicit Modules (Definitive fix for Xcode 16 / Yoga errors)
    installer.aggregate_targets.each do |target|
      target.user_project.targets.each do |p_target|
        p_target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
        end
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        # Fix Yoga / glog C++20 strict errors with Xcode 26
        if target.name == 'Yoga' || target.name == 'glog'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end

    # Fix: paths with spaces break `/bin/sh -c "$WITH_ENVIRONMENT $SCRIPT_PHASES_SCRIPT"` in Xcode 26.
    # Replace the unquoted invocation with properly quoted args so word-splitting doesn't occur.
    project_path = installer.pods_project.path.to_s + "/project.pbxproj"
    pbxproj = File.read(project_path)
    if pbxproj.include?('/bin/sh -c \\"$WITH_ENVIRONMENT $SCRIPT_PHASES_SCRIPT\\"')
      pbxproj.gsub!(
        '/bin/sh -c \\"$WITH_ENVIRONMENT $SCRIPT_PHASES_SCRIPT\\"',
        '\\"$WITH_ENVIRONMENT\\" \\"$SCRIPT_PHASES_SCRIPT\\"'
      )
      File.write(project_path, pbxproj)
      puts "[Podfile patch] Fixed Generate Specs path-spaces quoting for Xcode 26"
    end

    # Patch fmt/base.h to disable consteval on ALL Apple Clang (Xcode 26 has a bug with it)
    fmt_base_h = "#{installer.sandbox.root}/fmt/include/fmt/base.h"
    if File.exist?(fmt_base_h)
      content = File.read(fmt_base_h)
      patched = content.gsub(
        '#elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L',
        '#elif defined(__apple_build_version__) // Patched: disable consteval on all Apple Clang (Xcode 26 bug)'
      )
      File.write(fmt_base_h, patched)
      puts "[Podfile patch] fmt/base.h consteval disabled for Apple Clang"
    end
  end



end
